### ISSUE TITLE
docker-compose.yml の書き方がわからん

### ISSUE THREAD

**Issue by MiyasakaKufu** [MiyasakaKufu/golang-study#8]
docker-compose.yml

```yml
version: "3"

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go_todo
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - go_todo
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_ROOT_PASSWORD=password
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=go_todo

volumes:
  db:

networks:
  go_todo:
    name: go_todo
    driver: bridge
```

Dockerfile

```Dockerfile
FROM golang:1.22.5-alpine

# Set the Current Working Directory inside the container
WORKDIR /app

# Go Modules を使用するための環境変数を設定
ENV GO111MODULE=on

# 必要なパッケージをインストール
RUN apk add --no-cache git

# go.mod と go.sum をコピー
COPY go.mod go.sum ./

# 依存関係をダウンロード
RUN go mod download

# アプリケーションのソースコードをコピー
COPY . /app/

# アプリケーションをビルド
RUN go build -a -installsuffix cgo -o main ./main.go
```
